SELECT  ORDERS.ORDERID, ORDERS.ORDERDATE, ORDERS.CUSTOMERID, ORDERLINES.PROD_ID, ORDERLINES.QUANTITY, PRODUCTS.PRICE
FROM    ORDERS 
INNER JOIN
        ORDERLINES ON ORDERS.ORDERID = ORDERLINES.ORDERID 
INNER JOIN
        PRODUCTS ON ORDERLINES.PROD_ID = PRODUCTS.PROD_ID